/**
 * Script to generate seed-data.ts from source_data.json
 *
 * This script:
 * 1. Reads the source_data.json file
 * 2. Parses the JSON data
 * 3. Generates a TypeScript file (seed-data.ts) with the data embedded as a constant
 *
 * Usage:
 *   npx ts-node src/database/seeds/generate-seed-data.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const SOURCE_DATA_PATH = path.join(
  __dirname,
  '../../modules/stations/source_data.json',
);
const OUTPUT_PATH = path.join(__dirname, 'seed-data.ts');

interface StationDataSource {
  version: string;
  lastUpdated: string;
  stations: any[];
}

function generateSeedDataFile() {
  console.log('🔄 Reading source_data.json...');

  // Read the source JSON file
  const rawData = fs.readFileSync(SOURCE_DATA_PATH, 'utf-8');
  const data: StationDataSource = JSON.parse(rawData);

  console.log(`✅ Loaded ${data.stations.length} stations from source file`);
  console.log(`📅 Version: ${data.version}, Last Updated: ${data.lastUpdated}`);

  // Generate TypeScript file content
  const fileContent = `/**
 * Auto-generated seed data
 * 
 * Generated from: source_data.json
 * Generated at: ${new Date().toISOString()}
 * Version: ${data.version}
 * Last Updated: ${data.lastUpdated}
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run 'npm run seed:generate' to regenerate from source_data.json
 */

export const SEED_DATA = ${JSON.stringify(data, null, 2)} as const;
`;

  // Write the generated file
  fs.writeFileSync(OUTPUT_PATH, fileContent, 'utf-8');

  console.log('✅ Successfully generated seed-data.ts');
  console.log(`📁 Output path: ${OUTPUT_PATH}`);
  console.log(`📊 Total stations: ${data.stations.length}`);
  console.log('');
  console.log('You can now run the seed command:');
  console.log('  npm run seed');
}

// Execute the generation
try {
  generateSeedDataFile();
} catch (error) {
  console.error('❌ Failed to generate seed-data.ts:', error);
  process.exit(1);
}
